RESTRICTIONS_TBL = {
    "assassin": {
        "class": "assassin",
        "min_str": 12,
        "min_dex": 12,
        "min_con": 6,
        "min_int": 11,
        "min_wis": 6,
        "min_cha": 0,
        "hit_die": "d6",
        "alignment": ["le", "ne", "ce"],
        "armor": ["leather", "studded"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "3 +1 every 4 lvl",
        "penalty_to_hit": -3,
    },
    "cleric": {
        "class": "cleric",
        "min_str": 6,
        "min_dex": 3,
        "min_con": 6,
        "min_int": 6,
        "min_wis": 9,
        "min_cha": 6,
        "hit_die": "d8",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["club", "flail", "hammer", "mace", "oil", "staff"],
        "proficiencies": "2 + 1 every 3 lvl",
        "penalty_to_hit": -3,
    },
    "druid": {
        "class": "druid",
        "min_str": 6,
        "min_dex": 6,
        "min_con": 6,
        "min_int": 6,
        "min_wis": 12,
        "min_cha": 15,
        "hit_die": "d8",
        "alignment": ["ln", "nn", "cn"],
        "armor": ["leather"],
        "shield": ["wooden"],
        "weapons_permitted": [
            "club",
            "dagger",
            "dart",
            "hammer",
            "oil",
            "scimitar",
            "sling",
            "spear",
            "staff",
        ],
        "proficiencies": "2 + 1 every 3 lvl",
        "penalty_to_hit": -4,
    },
    "fighter": {
        "class": "fighter",
        "min_str": 9,
        "min_dex": 6,
        "min_con": 7,
        "min_int": 3,
        "min_wis": 6,
        "min_cha": 6,
        "hit_die": "d10",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "4 + 1 every 2 lvl",
        "penalty_to_hit": -2,
    },
    "illusionist": {
        "class": "illusionist",
        "min_str": 6,
        "min_dex": 16,
        "min_con": 0,
        "min_int": 6,
        "min_wis": 6,
        "min_cha": 6,
        "hit_die": "d4",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["none"],
        "shield": ["none"],
        "weapons_permitted": ["dagger", "dart", "oil", "staff"],
        "proficiencies": "1 + 1 every 5 lvl",
        "penalty_to_hit": -5,
    },
    "magic_user": {
        "class": "magic_user",
        "min_str": 3,
        "min_dex": 6,
        "min_con": 6,
        "min_int": 9,
        "min_wis": 6,
        "min_cha": 6,
        "hit_die": "d4",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["none"],
        "shield": ["none"],
        "weapons_permitted": ["dagger", "dart", "oil", "staff"],
        "proficiencies": "1 + 1 every 5 lvl",
        "penalty_to_hit": -5,
    },
    "paladin": {
        "class": "paladin",
        "min_str": 12,
        "min_dex": 6,
        "min_con": 9,
        "min_int": 9,
        "min_wis": 13,
        "min_cha": 17,
        "hit_die": "d10",
        "alignment": ["lg"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "3 + 1 every 2 lvl",
        "penalty_to_hit": -2,
    },
    "thief": {
        "class": "thief",
        "min_str": 6,
        "min_dex": 9,
        "min_con": 6,
        "min_int": 0,
        "min_wis": 0,
        "min_cha": 6,
        "hit_die": "d6",
        "alignment": ["ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["leather", "studded"],
        "shield": ["none"],
        "weapons_permitted": [
            "club",
            "dagger",
            "dart",
            "oil",
            "sling",
            "single_handed_swords",
        ],
        "proficiencies": "2 +1 every 4 lvl",
        "penalty_to_hit": -3,
    },
    "ranger": {
        "class": "ranger",
        "min_str": 13,
        "min_dex": 6,
        "min_con": 14,
        "min_int": 13,
        "min_wis": 14,
        "min_cha": 6,
        "hit_die": "d8",
        "alignment": ["lg", "ng", "cg"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "3 + 1 every 2 lvl",
        "penalty_to_hit": -2,
    },
}
