SAVING_THROWS = {
    "assassin": {
        1: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        2: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        3: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        4: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        5: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        6: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        7: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        8: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        9: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        10: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        11: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        12: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        13: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        14: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        15: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
    },
    "cleric": {
        1: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        2: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        3: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        4: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        5: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        6: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        7: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        8: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        9: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        10: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        11: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        12: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        13: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        14: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        15: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        16: {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 4,
            "breath_weapons": 10,
        },
        17: {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 4,
            "breath_weapons": 10,
        },
        18: {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 4,
            "breath_weapons": 10,
        },
        19: {
            "petrifaction_polymorph": "5",
            "unlisted": "7",
            "aimed_magic_items": "6",
            "death_paralysis_poison": "2",
            "breath_weapons": "8",
        },
    },
    "thief": {
        1: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        2: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        3: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        4: {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        5: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        6: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        7: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        8: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        9: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        10: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        11: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        12: {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        13: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        14: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        15: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        16: {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        17: {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        18: {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        19: {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        20: {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        21: {
            "petrifaction_polymorph": "7",
            "unlisted": "5",
            "aimed_magic_items": "4",
            "death_paralysis_poison": "8",
            "breath_weapons": "11",
        },
    },
    "paladin": {
        1: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        2: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        3: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        4: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        5: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 9,
            "breath_weapons": 11,
        },
        6: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 9,
            "breath_weapons": 11,
        },
        7: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 10,
        },
        8: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 10,
        },
        9: {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 6,
            "breath_weapons": 7,
        },
        10: {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 6,
            "breath_weapons": 7,
        },
        11: {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 6,
        },
        12: {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 6,
        },
        13: {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 3,
        },
        14: {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 3,
        },
        15: {
            "petrifaction_polymorph": 3,
            "unlisted": 5,
            "aimed_magic_items": 4,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        16: {
            "petrifaction_polymorph": 3,
            "unlisted": 5,
            "aimed_magic_items": 4,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        17: {
            "petrifaction_polymorph": 2,
            "unlisted": 4,
            "aimed_magic_items": 3,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        18: {
            "petrifaction_polymorph": 2,
            "unlisted": 4,
            "aimed_magic_items": 3,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        19: {
            "petrifaction_polymorph": "2",
            "unlisted": "3",
            "aimed_magic_items": "2",
            "death_paralysis_poison": "2",
            "breath_weapons": "2",
        },
    },
    "magic_user": {
        1: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        2: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        3: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        4: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        5: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        6: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        7: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        8: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        9: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        10: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        11: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        12: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        13: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        14: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        15: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        16: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        17: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        18: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        19: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        20: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        21: {
            "petrifaction_polymorph": "5",
            "unlisted": "4",
            "aimed_magic_items": "3",
            "death_paralysis_poison": "8",
            "breath_weapons": "7",
        },
    },
    "ranger": {
        1: {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        2: {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        3: {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        4: {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        5: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        6: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        7: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        8: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        9: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        10: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        11: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        12: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        13: {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        14: {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        15: {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        16: {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        17: {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        18: {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        19: {
            "petrifaction_polymorph": "3",
            "unlisted": "5",
            "aimed_magic_items": "4",
            "death_paralysis_poison": "2",
            "breath_weapons": "3",
        },
    },
    "illusionist": {
        1: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        2: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        3: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        4: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        5: {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        6: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        7: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        8: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        9: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        10: {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        11: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        12: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        13: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        14: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        15: {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        16: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        17: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        18: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        19: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        20: {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        21: {
            "petrifaction_polymorph": "5",
            "unlisted": "4",
            "aimed_magic_items": "3",
            "death_paralysis_poison": "8",
            "breath_weapons": "7",
        },
    },
    "druid": {
        1: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        2: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        3: {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        4: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        5: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        6: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        7: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        8: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        9: {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        10: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        11: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        12: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        13: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        14: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
    },
    "fighter": {
        0: {
            "petrifaction_polymorph": "17",
            "unlisted": "19",
            "aimed_magic_items": "18",
            "death_paralysis_poison": "16",
            "breath_weapons": "20",
        },
        1: {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        2: {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        3: {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        4: {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        5: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        6: {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        7: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        8: {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        9: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        10: {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        11: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        12: {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        13: {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        14: {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        15: {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        16: {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        17: {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        18: {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        19: {
            "petrifaction_polymorph": "3",
            "unlisted": "5",
            "aimed_magic_items": "4",
            "death_paralysis_poison": "2",
            "breath_weapons": "3",
        },
    },
}
