RESTRICTIONS_DICT = {
    "assassin": {
        "min_str": 12,
        "min_dex": 12,
        "min_con": 6,
        "min_int": 11,
        "min_wis": 6,
        "min_cha": 0,
        "hit_die": "d6",
        "alignment": ["le", "ne", "ce"],
        "armor": ["leather", "studded"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "3 +1 every 4 lvl",
        "penalty_to_hit": -3,
    },
    "cleric": {
        "min_str": 6,
        "min_dex": 3,
        "min_con": 6,
        "min_int": 6,
        "min_wis": 9,
        "min_cha": 6,
        "hit_die": "d8",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["club", "flail", "hammer", "mace", "oil", "staff"],
        "proficiencies": "2 + 1 every 3 lvl",
        "penalty_to_hit": -3,
    },
    "druid": {
        "min_str": 6,
        "min_dex": 6,
        "min_con": 6,
        "min_int": 6,
        "min_wis": 12,
        "min_cha": 15,
        "hit_die": "d8",
        "alignment": ["ln", "nn", "cn"],
        "armor": ["leather"],
        "shield": ["wooden"],
        "weapons_permitted": [
            "club",
            "dagger",
            "dart",
            "hammer",
            "oil",
            "scimitar",
            "sling",
            "spear",
            "staff",
        ],
        "proficiencies": "2 + 1 every 3 lvl",
        "penalty_to_hit": -4,
    },
    "fighter": {
        "min_str": 9,
        "min_dex": 6,
        "min_con": 7,
        "min_int": 3,
        "min_wis": 6,
        "min_cha": 6,
        "hit_die": "d10",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "4 + 1 every 2 lvl",
        "penalty_to_hit": -2,
    },
    "illusionist": {
        "min_str": 6,
        "min_dex": 16,
        "min_con": 0,
        "min_int": 6,
        "min_wis": 6,
        "min_cha": 6,
        "hit_die": "d4",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["none"],
        "shield": ["none"],
        "weapons_permitted": ["dagger", "dart", "oil", "staff"],
        "proficiencies": "1 + 1 every 5 lvl",
        "penalty_to_hit": -5,
    },
    "magic_user": {
        "min_str": 3,
        "min_dex": 6,
        "min_con": 6,
        "min_int": 9,
        "min_wis": 6,
        "min_cha": 6,
        "hit_die": "d4",
        "alignment": ["lg", "ng", "cg", "ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["none"],
        "shield": ["none"],
        "weapons_permitted": ["dagger", "dart", "oil", "staff"],
        "proficiencies": "1 + 1 every 5 lvl",
        "penalty_to_hit": -5,
    },
    "paladin": {
        "min_str": 12,
        "min_dex": 6,
        "min_con": 9,
        "min_int": 9,
        "min_wis": 13,
        "min_cha": 17,
        "hit_die": "d10",
        "alignment": ["lg"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "3 + 1 every 2 lvl",
        "penalty_to_hit": -2,
    },
    "thief": {
        "min_str": 6,
        "min_dex": 9,
        "min_con": 6,
        "min_int": 0,
        "min_wis": 0,
        "min_cha": 6,
        "hit_die": "d6",
        "alignment": ["ln", "nn", "cn", "le", "ne", "ce"],
        "armor": ["leather", "studded"],
        "shield": ["none"],
        "weapons_permitted": [
            "club",
            "dagger",
            "dart",
            "oil",
            "sling",
            "single_handed_swords",
        ],
        "proficiencies": "2 +1 every 4 lvl",
        "penalty_to_hit": -3,
    },
    "ranger": {
        "min_str": 13,
        "min_dex": 6,
        "min_con": 14,
        "min_int": 13,
        "min_wis": 14,
        "min_cha": 6,
        "hit_die": "d8",
        "alignment": ["lg", "ng", "cg"],
        "armor": ["any"],
        "shield": ["any"],
        "weapons_permitted": ["any"],
        "proficiencies": "3 + 1 every 2 lvl",
        "penalty_to_hit": -2,
    },
}

SAVING_THROWS_DICT = {
    "assassin": {
        "1": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "2": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "3": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "4": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "5": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "6": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "7": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "8": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "9": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "10": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "11": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "12": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "13": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        "14": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        "15": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
    },
    "cleric": {
        "1": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        "2": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        "3": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        "4": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        "5": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        "6": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        "7": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        "8": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        "9": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        "10": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        "11": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        "12": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        "13": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        "14": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        "15": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        "16": {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 4,
            "breath_weapons": 10,
        },
        "17": {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 4,
            "breath_weapons": 10,
        },
        "18": {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 4,
            "breath_weapons": 10,
        },
        "19": {
            "petrifaction_polymorph": "5",
            "unlisted": "7",
            "aimed_magic_items": "6",
            "death_paralysis_poison": "2",
            "breath_weapons": "8",
        },
    },
    "thief": {
        "1": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "2": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "3": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "4": {
            "petrifaction_polymorph": 12,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "5": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "6": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "7": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "8": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "9": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "10": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "11": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "12": {
            "petrifaction_polymorph": 10,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "13": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        "14": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        "15": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        "16": {
            "petrifaction_polymorph": 9,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 10,
            "breath_weapons": 13,
        },
        "17": {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        "18": {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        "19": {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        "20": {
            "petrifaction_polymorph": 8,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 9,
            "breath_weapons": 12,
        },
        "21": {
            "petrifaction_polymorph": "7",
            "unlisted": "5",
            "aimed_magic_items": "4",
            "death_paralysis_poison": "8",
            "breath_weapons": "11",
        },
    },
    "paladin": {
        "1": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "2": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 12,
            "breath_weapons": 15,
        },
        "3": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "4": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 14,
        },
        "5": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 9,
            "breath_weapons": 11,
        },
        "6": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 9,
            "breath_weapons": 11,
        },
        "7": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 10,
        },
        "8": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 10,
        },
        "9": {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 6,
            "breath_weapons": 7,
        },
        "10": {
            "petrifaction_polymorph": 7,
            "unlisted": 9,
            "aimed_magic_items": 8,
            "death_paralysis_poison": 6,
            "breath_weapons": 7,
        },
        "11": {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 6,
        },
        "12": {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 6,
        },
        "13": {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 3,
        },
        "14": {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 3,
        },
        "15": {
            "petrifaction_polymorph": 3,
            "unlisted": 5,
            "aimed_magic_items": 4,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        "16": {
            "petrifaction_polymorph": 3,
            "unlisted": 5,
            "aimed_magic_items": 4,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        "17": {
            "petrifaction_polymorph": 2,
            "unlisted": 4,
            "aimed_magic_items": 3,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        "18": {
            "petrifaction_polymorph": 2,
            "unlisted": 4,
            "aimed_magic_items": 3,
            "death_paralysis_poison": 2,
            "breath_weapons": 2,
        },
        "19": {
            "petrifaction_polymorph": "2",
            "unlisted": "3",
            "aimed_magic_items": "2",
            "death_paralysis_poison": "2",
            "breath_weapons": "2",
        },
    },
    "magic_user": {
        "1": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "2": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "3": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "4": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "5": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "6": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "7": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "8": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "9": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "10": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "11": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "12": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "13": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "14": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "15": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "16": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "17": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "18": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "19": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "20": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "21": {
            "petrifaction_polymorph": "5",
            "unlisted": "4",
            "aimed_magic_items": "3",
            "death_paralysis_poison": "8",
            "breath_weapons": "7",
        },
    },
    "ranger": {
        "1": {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        "2": {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        "3": {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "4": {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "5": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        "6": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        "7": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        "8": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        "9": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        "10": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        "11": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        "12": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        "13": {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        "14": {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        "15": {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        "16": {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        "17": {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        "18": {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        "19": {
            "petrifaction_polymorph": "3",
            "unlisted": "5",
            "aimed_magic_items": "4",
            "death_paralysis_poison": "2",
            "breath_weapons": "3",
        },
    },
    "illusionist": {
        "1": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "2": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "3": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "4": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "5": {
            "petrifaction_polymorph": 13,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 14,
            "breath_weapons": 15,
        },
        "6": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "7": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "8": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "9": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "10": {
            "petrifaction_polymorph": 11,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 13,
            "breath_weapons": 13,
        },
        "11": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "12": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "13": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "14": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "15": {
            "petrifaction_polymorph": 9,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 11,
            "breath_weapons": 11,
        },
        "16": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "17": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "18": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "19": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "20": {
            "petrifaction_polymorph": 7,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 10,
            "breath_weapons": 9,
        },
        "21": {
            "petrifaction_polymorph": "5",
            "unlisted": "4",
            "aimed_magic_items": "3",
            "death_paralysis_poison": "8",
            "breath_weapons": "7",
        },
    },
    "druid": {
        "1": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        "2": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        "3": {
            "petrifaction_polymorph": 13,
            "unlisted": 15,
            "aimed_magic_items": 14,
            "death_paralysis_poison": 10,
            "breath_weapons": 16,
        },
        "4": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        "5": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        "6": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 9,
            "breath_weapons": 15,
        },
        "7": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        "8": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        "9": {
            "petrifaction_polymorph": 10,
            "unlisted": 12,
            "aimed_magic_items": 11,
            "death_paralysis_poison": 7,
            "breath_weapons": 13,
        },
        "10": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        "11": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        "12": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 6,
            "breath_weapons": 12,
        },
        "13": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
        "14": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 5,
            "breath_weapons": 11,
        },
    },
    "fighter": {
        "0": {
            "petrifaction_polymorph": "17",
            "unlisted": "19",
            "aimed_magic_items": "18",
            "death_paralysis_poison": "16",
            "breath_weapons": "20",
        },
        "1": {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        "2": {
            "petrifaction_polymorph": 15,
            "unlisted": 17,
            "aimed_magic_items": 16,
            "death_paralysis_poison": 14,
            "breath_weapons": 17,
        },
        "3": {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "4": {
            "petrifaction_polymorph": 14,
            "unlisted": 16,
            "aimed_magic_items": 15,
            "death_paralysis_poison": 13,
            "breath_weapons": 16,
        },
        "5": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        "6": {
            "petrifaction_polymorph": 12,
            "unlisted": 14,
            "aimed_magic_items": 13,
            "death_paralysis_poison": 11,
            "breath_weapons": 13,
        },
        "7": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        "8": {
            "petrifaction_polymorph": 11,
            "unlisted": 13,
            "aimed_magic_items": 12,
            "death_paralysis_poison": 10,
            "breath_weapons": 12,
        },
        "9": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        "10": {
            "petrifaction_polymorph": 9,
            "unlisted": 11,
            "aimed_magic_items": 10,
            "death_paralysis_poison": 8,
            "breath_weapons": 9,
        },
        "11": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        "12": {
            "petrifaction_polymorph": 8,
            "unlisted": 10,
            "aimed_magic_items": 9,
            "death_paralysis_poison": 7,
            "breath_weapons": 8,
        },
        "13": {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        "14": {
            "petrifaction_polymorph": 6,
            "unlisted": 8,
            "aimed_magic_items": 7,
            "death_paralysis_poison": 5,
            "breath_weapons": 5,
        },
        "15": {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        "16": {
            "petrifaction_polymorph": 5,
            "unlisted": 7,
            "aimed_magic_items": 6,
            "death_paralysis_poison": 4,
            "breath_weapons": 4,
        },
        "17": {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        "18": {
            "petrifaction_polymorph": 4,
            "unlisted": 6,
            "aimed_magic_items": 5,
            "death_paralysis_poison": 3,
            "breath_weapons": 4,
        },
        "19": {
            "petrifaction_polymorph": "3",
            "unlisted": "5",
            "aimed_magic_items": "4",
            "death_paralysis_poison": "2",
            "breath_weapons": "3",
        },
    },
}

TO_HIT_DICT = {
    "assassin": {
        "1": 11,
        "2": 11,
        "3": 11,
        "4": 11,
        "5": 9,
        "6": 9,
        "7": 9,
        "8": 9,
        "9": 6,
        "10": 6,
        "11": 6,
        "12": 6,
        "13": 4,
        "14": 4,
        "15": 4,
    },
    "cleric": {
        "1": 10,
        "2": 10,
        "3": 10,
        "4": 8,
        "5": 8,
        "6": 8,
        "7": 6,
        "8": 6,
        "9": 6,
        "10": 4,
        "11": 4,
        "12": 4,
        "13": 2,
        "14": 2,
        "15": 2,
        "16": 0,
        "17": 0,
        "18": 0,
        "19": -1,
    },
    "druid": {
        "1": 10,
        "2": 10,
        "3": 10,
        "4": 8,
        "5": 8,
        "6": 8,
        "7": 6,
        "8": 6,
        "9": 6,
        "10": 4,
        "11": 4,
        "12": 4,
        "13": 2,
        "14": 2,
    },
    "fighter": {
        "0": 11,
        "1": 10,
        "2": 9,
        "3": 8,
        "4": 7,
        "5": 6,
        "6": 5,
        "7": 4,
        "8": 3,
        "9": 2,
        "10": 1,
        "11": 0,
        "12": -1,
        "13": -2,
        "14": -3,
        "15": -4,
        "16": -5,
        "17": -6,
        "18": -7,
        "19": -8,
        "20": -9,
    },
    "illusionist": {
        "1": 11,
        "2": 11,
        "3": 11,
        "4": 11,
        "5": 11,
        "6": 9,
        "7": 9,
        "8": 9,
        "9": 9,
        "10": 9,
        "11": 7,
        "12": 7,
        "13": 7,
        "14": 7,
        "15": 7,
        "16": 5,
        "17": 5,
        "18": 5,
        "19": 5,
        "20": 5,
        "21": 3,
    },
    "magic_user": {
        "1": 11,
        "2": 11,
        "3": 11,
        "4": 11,
        "5": 11,
        "6": 9,
        "7": 9,
        "8": 9,
        "9": 9,
        "10": 9,
        "11": 7,
        "12": 7,
        "13": 7,
        "14": 7,
        "15": 7,
        "16": 5,
        "17": 5,
        "18": 5,
        "19": 5,
        "20": 5,
        "21": 3,
    },
    "paladin": {
        "1": 10,
        "2": 9,
        "3": 8,
        "4": 7,
        "5": 6,
        "6": 5,
        "7": 4,
        "8": 3,
        "9": 2,
        "10": 1,
        "11": 0,
        "12": -1,
        "13": -2,
        "14": -3,
        "15": -4,
        "16": -5,
        "17": -6,
        "18": -7,
        "19": -8,
        "20": -9,
    },
    "thief": {
        "1": 11,
        "2": 11,
        "3": 11,
        "4": 11,
        "5": 9,
        "6": 9,
        "7": 9,
        "8": 9,
        "9": 6,
        "10": 6,
        "11": 6,
        "12": 6,
        "13": 4,
        "14": 4,
        "15": 4,
        "16": 4,
        "17": 2,
        "18": 2,
        "19": 2,
        "20": 2,
        "21": 0,
    },
    "ranger": {
        "1": 10,
        "2": 9,
        "3": 8,
        "4": 7,
        "5": 6,
        "6": 5,
        "7": 4,
        "8": 3,
        "9": 2,
        "10": 1,
        "11": 0,
        "12": -1,
        "13": -2,
        "14": -3,
        "15": -4,
        "16": -5,
        "17": -6,
        "18": -7,
        "19": -8,
        "20": -9,
    },
}
