from ..models import ThiefChance
THIEF_DEX_ADJ = [
    {
        "level": 9,
        "climb_walls": 0,
        "find_traps": -0.15,
        "hear_noise": 0,
        "hide_in_shadows": -0.1,
        "move_quietly": -0.2,
        "open_locks": -0.1,
        "pick_pockets": -0.15,
        "read_languages": 0,
    },
    {
        "level": 10,
        "climb_walls": 0,
        "find_traps": -0.1,
        "hear_noise": 0,
        "hide_in_shadows": -0.05,
        "move_quietly": -0.15,
        "open_locks": -0.05,
        "pick_pockets": -0.1,
        "read_languages": 0,
    },
    {
        "level": 11,
        "climb_walls": 0,
        "find_traps": -0.05,
        "hear_noise": 0,
        "hide_in_shadows": 0,
        "move_quietly": -0.1,
        "open_locks": 0,
        "pick_pockets": -0.05,
        "read_languages": 0,
    },
    {
        "level": 12,
        "climb_walls": 0,
        "find_traps": 0,
        "hear_noise": 0,
        "hide_in_shadows": 0,
        "move_quietly": -0.05,
        "open_locks": 0,
        "pick_pockets": 0,
        "read_languages": 0,
    },
    {
        "level": 16,
        "climb_walls": 0,
        "find_traps": 0,
        "hear_noise": 0,
        "hide_in_shadows": 0,
        "move_quietly": 0,
        "open_locks": 0.05,
        "pick_pockets": 0,
        "read_languages": 0,
    },
    {
        "level": 17,
        "climb_walls": 0,
        "find_traps": 0.05,
        "hear_noise": 0,
        "hide_in_shadows": 0.05,
        "move_quietly": 0.05,
        "open_locks": 0.1,
        "pick_pockets": 0,
        "read_languages": 0,
    },
    {
        "level": 18,
        "climb_walls": 0,
        "find_traps": 0.1,
        "hear_noise": 0,
        "hide_in_shadows": 0.1,
        "move_quietly": 0.1,
        "open_locks": 0.15,
        "pick_pockets": 0.05,
        "read_languages": 0,
    },
    {
        "level": 19,
        "climb_walls": 0,
        "find_traps": 0.15,
        "hear_noise": 0,
        "hide_in_shadows": 0.15,
        "move_quietly": 0.15,
        "open_locks": 0.2,
        "pick_pockets": 0.15,
        "read_languages": 0,
    },
]

THIEF_RACE_ADJ = {
    "dwarf": ThiefChance(
        climb_walls=-0.1,
        find_traps=0.15,
        hear_noise=0,
        hide_in_shadows=0,
        move_quietly=-0.05,
        open_locks=0.15,
        pick_pockets=0.15,
        read_languages=-0.05,
    ),
    "elf": ThiefChance(
        climb_walls=-0.05,
        find_traps=0.05,
        hear_noise=0.05,
        hide_in_shadows=0.1,
        move_quietly=0.05,
        open_locks=-0.05,
        pick_pockets=0.05,
        read_languages=0.1,
    ),
    "gnome": ThiefChance(
        climb_walls=-0.15,
        find_traps=0,
        hear_noise=0.05,
        hide_in_shadows=0,
        move_quietly=0,
        open_locks=0.1,
        pick_pockets=0,
        read_languages=0,
    ),
    "half_elf": ThiefChance(
        climb_walls=0,
        find_traps=0,
        hear_noise=0,
        hide_in_shadows=0.05,
        move_quietly=0,
        open_locks=0,
        pick_pockets=0.1,
        read_languages=0,
    ),
    "halfling": ThiefChance(
        climb_walls=-0.15,
        find_traps=0,
        hear_noise=0.05,
        hide_in_shadows=0.15,
        move_quietly=0.15,
        open_locks=0,
        pick_pockets=0.05,
        read_languages=-0.05,
    ),
    "half_orc": ThiefChance(
        climb_walls=0.05,
        find_traps=0.05,
        hear_noise=0.05,
        hide_in_shadows=0,
        move_quietly=0,
        open_locks=0.05,
        pick_pockets=-0.05,
        read_languages=-0.1,
    ),
    "human": ThiefChance(
        climb_walls=0.05,
        find_traps=0,
        hear_noise=0,
        hide_in_shadows=0,
        move_quietly=0,
        open_locks=0.05,
        pick_pockets=0,
        read_languages=0,
    ),
}
