"""empty message

Revision ID: 2e660a897e44
Revises: 
Create Date: 2020-02-17 20:33:21.076107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e660a897e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('char_name', sa.String(length=64), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_player_name'), 'player', ['player_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_player_name'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
